spring.application.name=session13_ex03

# datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/Session13
spring.datasource.username=postgres
spring.datasource.password=S1mpL0rd

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true